# Test 2026-02-05 at 02:47:17

name: Test
run-name: btreeList

on:
  push:
    paths:
      - '**/main.yml'

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
# cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Btree, Slots, Test]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK'
      uses: oracle-actions/setup-java@v1

    - name: Verilog install
      run: |
        sudo apt install iverilog yosys tree

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        tree
        cp Btree.java Slots.java Test.java com/AppaApps/Silicon

    - name: Java
      run: |
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/*.java

    - name: Test Btree
      if: matrix.task == 'Btree'
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Btree


    - name: Test Slots
      if: matrix.task == 'Slots'
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Slots


    - name: Test Test
      if: matrix.task == 'Test'
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Test

